export const ADD_CATEGORY_SUCC = 'A_ADD_CATEGORY_SUCC';
export const ADD_TEACHER_SUCC = 'A_ADD_TEACHER_SUCC';
export const GET_COMMENTS_SUCC = 'A_GET_COMMENTS_SUCC';
export const ADD_FILE_TO_COURSE = 'A_ADD_FILE_TO_COURSE';
export const SET_SETTINGS_SUCC = 'A_SET_SETTINGS_SUCC';